<?php

namespace Fobia\DataBase\Query;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-24 at 06:56:20.
 */
class QueryInsertTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \Fobia\DataBase\Handler\MySQL
     */
    protected $db;

    protected function setUp()
    {
        if ( ! $this->db) {
            $this->db = \Fobia\DataBase\DbFactory::create('mysql://root@localhost/mysql');
        }
    }

    public function testInsertIntoIgnore()
    {
        $q = $this->db->createInsertQuery();
        $q->insertIntoIgnore('user');
        $this->assertInstanceOf('\Fobia\DataBase\Query\QueryInsert', $q);
    }

    public function testGetQuery()
    {
        $q = $this->db->createInsertQuery();

        $str = "INSERT IGNORE INTO user ( Host, User, Password ) VALUES ( 'localhost', 'test', '' )";
        $q->insertIntoIgnore('user')
                ->set('Host', $this->db->quote('localhost'))
                ->set('User', $this->db->quote('test'))
                ->set('Password', $this->db->quote(''));
        $this->assertEquals($str, $q->getQuery());
    }
}