<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ezcbase' => '/base/base.php',
                'ezcbaseautoloadexception' => '/base/exceptions/autoload.php',
                'ezcbaseautoloadoptions' => '/base/options/autoload.php',
                'ezcbaseconfigurationinitializer' => '/base/interfaces/configuration_initializer.php',
                'ezcbasedoubleclassrepositoryprefixexception' => '/base/exceptions/double_class_repository_prefix.php',
                'ezcbaseexception' => '/base/exceptions/exception.php',
                'ezcbaseexportable' => '/base/interfaces/exportable.php',
                'ezcbaseextensionnotfoundexception' => '/base/exceptions/extension_not_found.php',
                'ezcbasefeatures' => '/base/features.php',
                'ezcbasefile' => '/base/file.php',
                'ezcbasefileexception' => '/base/exceptions/file_exception.php',
                'ezcbasefilefindcontext' => '/base/structs/file_find_context.php',
                'ezcbasefileioexception' => '/base/exceptions/file_io.php',
                'ezcbasefilenotfoundexception' => '/base/exceptions/file_not_found.php',
                'ezcbasefilepermissionexception' => '/base/exceptions/file_permission.php',
                'ezcbasefunctionalitynotsupportedexception' => '/base/exceptions/functionality_not_supported.php',
                'ezcbaseinit' => '/base/init.php',
                'ezcbaseinitcallbackconfiguredexception' => '/base/exceptions/init_callback_configured.php',
                'ezcbaseinitinvalidcallbackclassexception' => '/base/exceptions/invalid_callback_class.php',
                'ezcbaseinvalidparentclassexception' => '/base/exceptions/invalid_parent_class.php',
                'ezcbasemetadata' => '/base/metadata.php',
                'ezcbasemetadatapearreader' => '/base/metadata/pear.php',
                'ezcbasemetadatatarballreader' => '/base/metadata/tarball.php',
                'ezcbaseoptions' => '/base/options.php',
                'ezcbasepersistable' => '/base/interfaces/persistable.php',
                'ezcbasepropertynotfoundexception' => '/base/exceptions/property_not_found.php',
                'ezcbasepropertypermissionexception' => '/base/exceptions/property_permission.php',
                'ezcbaserepositorydirectory' => '/base/structs/repository_directory.php',
                'ezcbasesettingnotfoundexception' => '/base/exceptions/setting_not_found.php',
                'ezcbasesettingvalueexception' => '/base/exceptions/setting_value.php',
                'ezcbasestruct' => '/base/struct.php',
                'ezcbasevalueexception' => '/base/exceptions/value.php',
                'ezcbasewhateverexception' => '/base/exceptions/whatever.php',
                'ezcdbexception' => '/database/exceptions/exception.php',
                'ezcdbfactory' => '/database/factory.php',
                'ezcdbhandler' => '/database/handler.php',
                'ezcdbhandlermssql' => '/database/handlers/mssql.php',
                'ezcdbhandlermysql' => '/database/handlers/mysql.php',
                'ezcdbhandlernotfoundexception' => '/database/exceptions/handler_not_found.php',
                'ezcdbhandleroracle' => '/database/handlers/oracle.php',
                'ezcdbhandlerpgsql' => '/database/handlers/pgsql.php',
                'ezcdbhandlersqlite' => '/database/handlers/sqlite.php',
                'ezcdbinstance' => '/database/instance.php',
                'ezcdbinterface' => '/database/interface.php',
                'ezcdbmissingparameterexception' => '/database/exceptions/missing_parameter.php',
                'ezcdbmssqloptions' => '/database/options/identifiers.php',
                'ezcdbtransactionexception' => '/database/exceptions/transaction.php',
                'ezcdbutilities' => '/database/sqlabstraction/utilities.php',
                'ezcdbutilitiesmysql' => '/database/sqlabstraction/implementations/utilities_mysql.php',
                'ezcdbutilitiesoracle' => '/database/sqlabstraction/implementations/utilities_oracle.php',
                'ezcdbutilitiespgsql' => '/database/sqlabstraction/implementations/utilities_pgsql.php',
                'ezcdbutilitiessqlite' => '/database/sqlabstraction/implementations/utilities_sqlite.php',
                'ezcquery' => '/database/sqlabstraction/query.php',
                'ezcquerydelete' => '/database/sqlabstraction/query_delete.php',
                'ezcqueryexception' => '/database/exceptions/query_exception.php',
                'ezcqueryexpression' => '/database/sqlabstraction/expression.php',
                'ezcqueryexpressionmssql' => '/database/sqlabstraction/implementations/expression_mssql.php',
                'ezcqueryexpressionoracle' => '/database/sqlabstraction/implementations/expression_oracle.php',
                'ezcqueryexpressionpgsql' => '/database/sqlabstraction/implementations/expression_pgsql.php',
                'ezcqueryexpressionsqlite' => '/database/sqlabstraction/implementations/expression_sqlite.php',
                'ezcqueryinsert' => '/database/sqlabstraction/query_insert.php',
                'ezcqueryinvalidexception' => '/database/exceptions/query/invalid.php',
                'ezcqueryinvalidparameterexception' => '/database/exceptions/query/invalid_parameter.php',
                'ezcqueryselect' => '/database/sqlabstraction/query_select.php',
                'ezcqueryselectmssql' => '/database/sqlabstraction/implementations/query_select_mssql.php',
                'ezcqueryselectoracle' => '/database/sqlabstraction/implementations/query_select_oracle.php',
                'ezcqueryselectsqlite' => '/database/sqlabstraction/implementations/query_select_sqlite.php',
                'ezcquerysqlitefunctions' => '/database/sqlabstraction/implementations/query_sqlite_function_implementations.php',
                'ezcquerysubselect' => '/database/sqlabstraction/query_subselect.php',
                'ezcqueryupdate' => '/database/sqlabstraction/query_update.php',
                'ezcqueryvariableparameterexception' => '/database/exceptions/query/variable_parameter.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
